(function(){
  'use strict';
  const M=window.FunctionalLab,$=id=>document.getElementById(id),KEY='hau-functional-response-v1';
  let data={version:1,experiments:[],activeId:null},running=null,raf=null,toastTimer=null,selectedId=null;
  const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const seed=()=>crypto.getRandomValues(new Uint32Array(1))[0];
  const round=n=>Math.round(n*1000)/1000;
  const current=()=>data.experiments.find(e=>e.id===data.activeId);
  const selected=()=>data.experiments.find(e=>e.id===selectedId)||current();
  const total=()=>data.experiments.reduce((s,e)=>s+e.trials.length,0);
  function notify(message){clearTimeout(toastTimer);$('toast').textContent=message;$('toast').classList.remove('hidden');toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),6000);}
  function save(){try{localStorage.setItem(KEY,JSON.stringify(data));}catch{$('storage-warning').classList.remove('hidden');}}
  function restore(){try{const text=localStorage.getItem(KEY);if(text){const d=JSON.parse(text);if(d.version!==1||!Array.isArray(d.experiments))throw Error('Invalid saved data');for(const e of d.experiments){M.validate({...e.config,densities:e.config.densities.join(',')});if(!Array.isArray(e.trials)||!Array.isArray(e.schedule))throw Error('Invalid saved experiment');}data=d;}}catch{notify('Saved data could not be loaded. This session is ready for a new experiment.');} }
  function ask(title,message,label='Continue'){return new Promise(resolve=>{$('confirm-title').textContent=title;$('confirm-message').textContent=message;$('confirm-yes').textContent=label;const d=$('confirm-dialog');let answered=false;function finish(value){if(answered)return;answered=true;d.close();d.oncancel=null;resolve(value);}$('confirm-yes').onclick=()=>finish(true);$('confirm-cancel').onclick=()=>finish(false);d.oncancel=ev=>{ev.preventDefault();finish(false);};d.showModal();});}
  function rawForm(){return Object.fromEntries(new FormData($('setup-form')));}
  function config(){return M.validate(rawForm());}
  function updateFormNotes(){const s=M.species[$('prey').value],p=M.predators[$('predator').value];$('prey-note').innerHTML='<i>'+escape(s.scientific)+'</i> · '+escape(s.crop);$('predator-note').innerHTML='<i>'+escape(p.scientific)+'</i> · '+escape(p.stage);try{const c=config();$('design-summary').textContent=c.densities.length+' densities × '+c.replicates+' replicates · '+round(c.densities.length*c.replicates*c.duration/60)+' min of trials';$('form-error').textContent='';if(!current()&&!running)$('time-display').innerHTML=c.duration.toFixed(1)+'<span>s</span>';}catch(e){$('design-summary').textContent='Check your settings before creating an experiment.';}}
  function fillForm(c){for(const [k,v]of Object.entries(c)){const input=$(k);if(input)input.value=k==='densities'?v.join(', '):v;}updateFormNotes();}
  function navigate(view){if(running){notify('Finish or discard this attempt before changing views.');return;}document.querySelectorAll('.view').forEach(el=>el.classList.toggle('hidden',el.id!=='view-'+view));document.querySelectorAll('.nav-button').forEach(el=>{const yes=el.dataset.view===view;el.classList.toggle('active',yes);if(yes)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current');});if(view==='results')renderResults();window.scrollTo({top:0,behavior:'instant'});}
  function conditionText(c){return M.species[c.prey].common+' · '+M.predators[c.predator].common+' · '+c.duration+' s trials · '+c.handling+' s handling · '+(c.replacement==='depletion'?'prey removed':'prey replaced')+' · '+(c.distribution==='random'?'scattered':'clustered')+' · '+(c.background==='plain'?'subtle veins':'prominent veins')+' · '+c.target+' targets';}
  async function createExperiment(ev){if(ev)ev.preventDefault();if(running)return;let c;try{c=config();}catch(e){$('form-error').textContent=e.message;return;}
    const old=current();if(old&&old.trials.length<old.schedule.length){if(!await ask('Start another experiment?','Your completed trials will remain in Results. This creates a new trial sequence using the current settings.','Create experiment'))return;}
    const id='exp-'+Date.now().toString(36)+'-'+seed().toString(36),designSeed=seed();
    const e={id,created:new Date().toISOString(),config:c,designSeed,schedule:M.schedule(c,designSeed),trials:[]};data.experiments.push(e);data.activeId=id;selectedId=id;save();renderSchedule();renderReady();updateCounts();notify('Experiment created. Each replicate block has a random density order.');
  }
  function updateCounts(){$('result-count').textContent=total();$('export-csv').disabled=!total();$('export-summary').disabled=!total();}
  function renderSchedule(){const e=current();$('create-experiment').textContent=e?'Create new experiment':'Create experiment';if(!e){$('schedule').innerHTML='<p class="empty-inline">Each replicate block includes every density, in a random order.</p>';$('schedule-progress').textContent='No experiment yet';$('current-conditions').textContent='One student acts as one predator. Rest between trials.';return;}
    $('schedule-progress').textContent=e.trials.length+' / '+e.schedule.length+' complete';$('schedule').innerHTML=e.schedule.map((r,i)=>'<div class="schedule-item '+(i<e.trials.length?'done':i===e.trials.length?'current':'')+' '+(i%e.config.densities.length===0?'block-start':'')+'" title="Trial '+r.order+', replicate '+r.replicate+', '+r.density+' aphids'+(i<e.trials.length?' — complete':'')+'"><span class="rep-label">R'+r.replicate+'</span>'+r.density+'</div>').join('');$('current-conditions').textContent=conditionText(e.config);
  }
  function cover(html){$('cover-content').innerHTML=html;$('arena-cover').classList.remove('hidden');$('handling-cover').classList.add('hidden');$('prey-layer').setAttribute('aria-hidden','true');$('prey-layer').inert=true;}
  function renderReady(){const e=current();$('activity-display').textContent='Ready';$('eaten-display').textContent='0';$('remaining-display').textContent='—';if(!e)return;
    const next=e.schedule[e.trials.length];$('time-display').innerHTML=e.config.duration.toFixed(1)+'<span>s</span>';$('arena').className='arena '+e.config.background;
    if(!next){$('trial-badge').textContent='Experiment complete';$('trial-instruction').textContent='All trials recorded. View your graph, then change one condition for a new experiment.';cover('<span class="cover-kicker">DATA COLLECTION COMPLETE</span><h3>You have a functional response to explore.</h3><p>'+e.trials.length+' trials across '+e.config.densities.length+' prey densities.</p><button class="light-button" data-view="results">Explore your results</button>');return;}
    $('trial-badge').textContent='Trial '+next.order+' of '+e.schedule.length;$('trial-instruction').textContent='Replicate '+next.replicate+' · '+next.density+' aphids · '+e.config.duration+' seconds. Click Start when you are ready.';
    cover('<span class="cover-kicker">REPLICATE '+next.replicate+' · TRIAL '+next.order+'</span><h3>'+next.density+' aphids. '+e.config.duration+' seconds.</h3><p>'+escape(M.species[e.config.prey].common)+' · '+e.config.handling+' s handling per prey.<br>Prey are '+(e.config.replacement==='depletion'?'removed after consumption.':'replaced after consumption.')+'</p><button id="start-trial" class="light-button">Start trial</button><p class="cover-small">Take a moment to rest. The timer starts when you click.</p>');
  }
  function spawnTarget(point){const r=running;if(!r)return;const c=r.config,button=document.createElement('button');button.type='button';button.className='aphid '+c.prey+(c.target==='large'?' large':'');button.dataset.target=point.id;button.style.left=(point.x/9)+'%';button.style.top=(point.y/5.4)+'%';button.style.setProperty('--rotation',point.angle+'deg');button.setAttribute('aria-label',M.species[c.prey].common);button.tabIndex=-1;const img=document.createElement('img');img.src='assets/'+M.species[c.prey].image;img.alt='';img.draggable=false;button.append(img);$('prey-layer').append(button);r.active.set(point.id,button);}
  function syncConsumption(){const r=running;while(r.renderedEvents<r.engine.events.length){const event=r.engine.events[r.renderedEvents++];const el=r.active.get(event.target);if(el)el.remove();r.active.delete(event.target);if(r.config.replacement==='replacement'&&!r.engine.finished){const vacant=r.cells.filter(p=>!r.active.has(p.id)&&p.id!==event.target);const pool=r.config.distribution==='clustered'?vacant.slice(0,Math.max(12,r.density)):vacant;const point=pool[Math.floor(r.random()*pool.length)];spawnTarget(point);}}}
  function startTrial(practice=false){if(running)return;let c,next;try{c=practice?config():current().config;}catch(e){$('form-error').textContent=e.message||'Create an experiment first.';return;}
    if(practice){c={...c,duration:10};next={density:20,replicate:0,order:0};}else{next=current().schedule[current().trials.length];if(!next)return;}
    const trialSeed=seed(),rect=$('arena').getBoundingClientRect();const cells=M.layout(trialSeed,c.target,c.distribution);running={practice,config:{...c},...next,trialSeed,engine:new M.TrialEngine(c,next.density),start:performance.now(),date:new Date().toISOString(),cells,active:new Map(),random:M.rng(trialSeed^0xa37b19),renderedEvents:0,inputs:new Set(),width:Math.round(rect.width),height:Math.round(rect.height),dpr:window.devicePixelRatio};
    $('prey-layer').replaceChildren();$('arena').className='arena '+c.background;cells.slice(0,next.density).forEach(spawnTarget);$('arena-cover').classList.add('hidden');$('handling-cover').classList.add('hidden');$('prey-layer').setAttribute('aria-hidden','false');$('prey-layer').inert=false;$('conditions').disabled=true;$('create-experiment').disabled=true;$('abort-trial').classList.remove('hidden');document.body.classList.add('running');$('trial-badge').textContent=practice?'Unrecorded practice':'Trial '+next.order+' of '+current().schedule.length;$('trial-instruction').textContent='Click an aphid. Wait for handling to finish. Only completed captures count.';frame();
  }
  function frame(){if(!running)return;const r=running,elapsed=(performance.now()-r.start)/1000;r.engine.advance(elapsed);syncConsumption();updateHud();if(r.engine.finished){finishTrial();return;}raf=requestAnimationFrame(frame);}
  function updateHud(){const r=running,e=r.engine;$('time-display').innerHTML=Math.max(0,r.config.duration-e.elapsed).toFixed(1)+'<span>s</span>';$('eaten-display').textContent=e.eaten;$('remaining-display').textContent=e.remaining;$('activity-display').textContent=e.pending?'Handling':e.remaining>0?'Searching':'Leaf cleared';$('handling-cover').classList.toggle('hidden',!e.pending);$('prey-layer').inert=!!e.pending;if(e.pending){const remaining=Math.max(0,e.pending.end-e.elapsed);$('handling-countdown').textContent=remaining.toFixed(1)+' s';$('handling-progress').style.transform='scaleX('+Math.min(1,remaining/r.config.handling)+')';}}
  function capture(ev){if(!running)return;const button=ev.target.closest('.aphid');const r=running;r.engine.advance((performance.now()-r.start)/1000);syncConsumption();if(r.engine.finished){finishTrial();return;}if(r.engine.pending)return;if(!button||!r.active.has(Number(button.dataset.target))){r.engine.misses++;return;}ev.preventDefault();r.inputs.add(ev.pointerType||'mouse');if(r.engine.capture(Number(button.dataset.target),(performance.now()-r.start)/1000)){syncConsumption();updateHud();}}
  function unlock(){cancelAnimationFrame(raf);raf=null;$('conditions').disabled=false;$('create-experiment').disabled=false;$('abort-trial').classList.add('hidden');document.body.classList.remove('running');$('handling-cover').classList.add('hidden');$('prey-layer').inert=true;}
  function finishTrial(){const r=running;if(!r)return;const result=r.engine.result();unlock();running=null;$('activity-display').textContent='Complete';$('time-display').innerHTML='0.0<span>s</span>';
    if(!r.practice){const e=current();e.trials.push({id:e.id+'-t'+r.order,order:r.order,replicate:r.replicate,density:r.density,duration:r.config.duration,...result,handlingSpent:round(result.handlingSpent),searchTime:round(result.searchTime),seed:r.trialSeed,date:r.date,arenaWidth:r.width,arenaHeight:r.height,dpr:r.dpr,input:[...r.inputs].sort().join('+')||'none',events:r.engine.events});selectedId=e.id;save();renderSchedule();updateCounts();}
    const allDone=!r.practice&&current().trials.length===current().schedule.length;const next=r.practice?current()?.schedule[current().trials.length]:current().schedule[current().trials.length];
    const mainButton=allDone?'<button class="light-button" data-view="results">Explore your results</button>':next?'<button id="next-trial" class="light-button">Prepare next trial · '+next.density+' aphids</button>':'<button id="practice-again" class="light-button">Practise again</button>';
    cover('<span class="cover-kicker">'+(r.practice?'PRACTICE COMPLETE · NOT RECORDED':allDone?'EXPERIMENT COMPLETE':'TRIAL RECORDED')+'</span><h3><span class="result-number">'+result.eaten+'</span>aphids consumed</h3><p>'+round(result.eaten/r.config.duration)+' aphids per second'+(result.unfinished?' · 1 unfinished capture excluded':'')+'</p>'+mainButton+(r.practice&&!current()?'<p class="cover-small">Use the settings panel to create your recorded experiment.</p>':''));
    $('trial-instruction').textContent=r.practice?'Practice is not included in your dataset.':allDone?'All trials complete. Your results are ready.':'Take a break. The next trial will wait for you.';
  }
  function abort(message='Attempt discarded. Completed trials are still saved.'){if(!running)return;const wasPractice=running.practice;unlock();running=null;$('prey-layer').replaceChildren();if(current())renderReady();else{cover('<span class="cover-kicker">PRACTICE INTERRUPTED</span><h3>Ready when you are.</h3><p>No data were recorded.</p><button id="practice-again" class="light-button">Try practice again</button>');$('activity-display').textContent='Ready';$('trial-instruction').textContent='Create an experiment, or try another practice.';}notify(message);}
  function value(r,metric){return metric==='rate'?r.eaten/r.duration:metric==='proportion'?r.eaten/r.density:r.eaten;}
  function renderResults(){updateCounts();const available=data.experiments.filter(e=>e.trials.length);$('results-empty').classList.toggle('hidden',available.length>0);$('results-content').classList.toggle('hidden',!available.length);if(!available.length)return;if(!available.some(e=>e.id===selectedId))selectedId=available[available.length-1].id;
    $('experiment-select').innerHTML=available.map(e=>'<option value="'+escape(e.id)+'"'+(e.id===selectedId?' selected':'')+'>'+escape((e.config.group?e.config.group+' · ':'')+'Experiment '+(data.experiments.indexOf(e)+1)+' · '+e.config.handling+' s handling · '+e.trials.length+' trials')+'</option>').join('');const e=selected();const replacement=e.config.replacement==='replacement';$('metric').querySelector('[value="proportion"]').disabled=replacement;if(replacement&&$('metric').value==='proportion')$('metric').value='eaten';$('result-conditions').textContent=conditionText(e.config);$('complete-trials').textContent=e.trials.length+' recorded trials';const summary=M.summary(e.trials);const complete=summary.filter(s=>s.n===e.config.replicates).length;$('result-observation').textContent=complete+' of '+e.config.densities.length+' densities have all '+e.config.replicates+' replicates. Compare how the mean and variation change as density increases.';
    $('model-description').textContent=(replacement?'Holling disc equation: constant prey density.':'Rogers random-predator equation: prey depleted during the trial.')+' Uses your '+e.config.handling+' s handling time and '+e.config.duration+' s trial length.';
    $('trial-table').innerHTML=e.trials.map(r=>'<tr><td>'+r.order+'</td><td>'+r.replicate+'</td><td>'+r.density+'</td><td>'+r.eaten+'</td><td>'+round(r.eaten/r.duration)+'</td><td>'+e.config.handling+'</td><td>'+(r.unfinished?'Yes · excluded':'No')+'</td></tr>').join('');renderChart();
  }
  function renderChart(){const e=selected();if(!e||!e.trials.length)return;const metric=$('metric').value,stats=M.summary(e.trials,metric),showModel=$('show-model').checked,a=Number($('attack-rate').value);const validA=Number.isFinite(a)&&a>=.001&&a<=5;const maxN=Math.max(...e.config.densities);const prediction=n=>{const v=M.typeII(n,a,e.config.handling,e.config.duration,e.config.replacement);return metric==='rate'?v/e.config.duration:metric==='proportion'?(n?v/n:0):v;};
    const model=showModel&&validA?Array.from({length:101},(_,i)=>({x:i*maxN/100,y:prediction(i*maxN/100)})):[];
    const maxY=metric==='proportion'?Math.max(1,...stats.map(s=>s.mean+(s.se||0))):Math.max(1,...e.trials.map(r=>value(r,metric)),...stats.map(s=>s.mean+(s.se||0)),...model.map(p=>p.y))*1.1;
    const W=800,H=450,l=76,rt=25,t=25,b=78,pw=W-l-rt,ph=H-t-b;const x=n=>l+(n/(maxN*1.04))*pw,y=n=>t+ph-n/maxY*ph;const fmt=n=>Number.isInteger(n)?String(n):n.toFixed(metric==='proportion'?2:1);const label=metric==='rate'?'Consumption rate (aphids/s)':metric==='proportion'?'Proportion of initial prey consumed':'Aphids consumed per trial';let svg='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 '+W+' '+H+'" role="img" aria-labelledby="graph-title graph-desc"><title id="graph-title">'+label+' against initial prey density</title><desc id="graph-desc">Individual completed trials and means with one standard error. '+escape(stats.map(s=>s.density+' aphids: mean '+s.mean.toFixed(2)+', n='+s.n).join('; '))+'.</desc><rect width="800" height="450" fill="white"/><g font-family="Arial, sans-serif" font-size="14" fill="#546b7b">';
    for(let i=0;i<=5;i++){const n=maxY*i/5;svg+='<path d="M'+l+' '+y(n)+'H'+(W-rt)+'" stroke="#e3eaf0"/><text x="'+(l-12)+'" y="'+(y(n)+5)+'" text-anchor="end">'+fmt(n)+'</text>';}
    for(const n of [0,...e.config.densities])svg+='<text x="'+x(n)+'" y="'+(H-b+27)+'" text-anchor="middle">'+n+'</text>';
    svg+='<path d="M'+l+' '+t+'V'+(H-b)+'H'+(W-rt)+'" fill="none" stroke="#8da2b2"/><text x="'+((l+W-rt)/2)+'" y="'+(H-20)+'" text-anchor="middle" fill="#15354c">Initial prey density (aphids per arena)</text><text transform="translate(21 '+(t+ph/2)+') rotate(-90)" text-anchor="middle" fill="#15354c">'+label+'</text>';
    if(model.length)svg+='<path d="'+model.map((p,i)=>(i?'L':'M')+x(p.x).toFixed(2)+','+y(p.y).toFixed(2)).join(' ')+'" fill="none" stroke="#c45b25" stroke-width="2.4" stroke-dasharray="7 5"/>';
    for(const r of e.trials){const jitter=(M.rng(r.seed)()-.5)*14;svg+='<circle cx="'+(x(r.density)+jitter)+'" cy="'+y(value(r,metric))+'" r="4.6" fill="#648da9" fill-opacity=".52"><title>Trial '+r.order+', replicate '+r.replicate+': '+value(r,metric).toFixed(3)+'</title></circle>';}
    svg+='<path d="'+stats.map((s,i)=>(i?'L':'M')+x(s.density)+','+y(s.mean)).join(' ')+'" fill="none" stroke="#0b2c48" stroke-width="2.5"/>';
    for(const s of stats){if(s.se!==null){const cx=x(s.density),top=y(s.mean+s.se),bottom=y(Math.max(0,s.mean-s.se));svg+='<path d="M'+cx+' '+top+'V'+bottom+'M'+(cx-5)+' '+top+'H'+(cx+5)+'M'+(cx-5)+' '+bottom+'H'+(cx+5)+'" stroke="#0b2c48" stroke-width="1.6"/>'; }svg+='<circle cx="'+x(s.density)+'" cy="'+y(s.mean)+'" r="5.5" stroke="white" stroke-width="2" fill="#0b2c48"/>';}
    svg+='</g></svg>';$('chart').innerHTML=svg;$('chart-note').textContent='Means are joined as a visual guide. SE is omitted when n = 1; horizontal point jitter separates overlapping trials.'+(model.length?' Orange dashed curve: theoretical type II, a = '+a+' arena/s; not fitted.':'')+(showModel&&!validA?' Enter a search coefficient from 0.001 to 5 to display the model.':'')+(e.config.replacement==='replacement'?' Consumption can exceed the initial prey count because prey are replaced.':'');
  }
  function download(text,name,type){const blob=new Blob([text],{type});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function metadata(e){const c=e.config;return{app_version:'1.0.0',experiment_id:e.id,group_code:c.group,aphid_species:M.species[c.prey].scientific,predator:M.predators[c.predator].scientific,predator_stage:M.predators[c.predator].stage,trial_duration_s:c.duration,handling_time_s:c.handling,prey_treatment:c.replacement,distribution:c.distribution,leaf_background:c.background,target_size:c.target,design_seed:e.designSeed,planned_replicates:c.replicates};}
  function exportTrials(){const rows=data.experiments.flatMap(e=>e.trials.map(r=>({...metadata(e),trial_order:r.order,replicate_block:r.replicate,initial_prey:r.density,consumed:r.eaten,consumption_rate_per_s:round(r.eaten/r.duration),proportion_consumed:e.config.replacement==='depletion'?round(r.eaten/r.density):'',captures_initiated:r.attacks,unfinished_capture:r.unfinished,missed_clicks:r.misses,handling_elapsed_s:r.handlingSpent,nonhandling_elapsed_s:r.searchTime,arena_seed:r.seed,arena_width_px:r.arenaWidth,arena_height_px:r.arenaHeight,device_pixel_ratio:r.dpr,input_type:r.input,started_at_utc:r.date,completion_times_s:r.events.map(v=>round(v.completed)).join(';')})));if(rows.length)download(M.csv(rows),'functional-response-trials.csv','text/csv;charset=utf-8');}
  function exportSummary(){const rows=data.experiments.flatMap(e=>M.summary(e.trials).map(s=>({...metadata(e),initial_prey:s.density,n:s.n,mean_consumed:round(s.mean),sd_consumed:s.sd===null?'':round(s.sd),se_consumed:s.se===null?'':round(s.se),mean_rate_per_s:round(s.mean/e.config.duration),mean_proportion_consumed:e.config.replacement==='depletion'?round(s.mean/s.density):''})));if(rows.length)download(M.csv(rows),'functional-response-summary.csv','text/csv;charset=utf-8');}
  document.addEventListener('click',ev=>{const n=ev.target.closest('[data-view]');if(n){navigate(n.dataset.view);return;}if(ev.target.id==='practice'||ev.target.id==='practice-again')startTrial(true);if(ev.target.id==='start-trial')startTrial(false);if(ev.target.id==='next-trial')renderReady();});
  $('setup-form').addEventListener('submit',createExperiment);$('setup-form').addEventListener('input',updateFormNotes);$('setup-form').addEventListener('change',updateFormNotes);$('prey-layer').addEventListener('pointerdown',capture);$('abort-trial').addEventListener('click',()=>abort());
  document.addEventListener('visibilitychange',()=>{if(document.hidden&&running)abort('Trial interrupted when the page was hidden. No data from this attempt were recorded.');});window.addEventListener('pagehide',()=>{if(running)abort();});window.addEventListener('resize',()=>{if(running){const r=$('arena').getBoundingClientRect();if(Math.abs(r.width-running.width)>2||Math.abs(r.height-running.height)>2)abort('The arena size changed. Repeat this attempt at a fixed window size.');}});
  $('experiment-select').addEventListener('change',()=>{selectedId=$('experiment-select').value;renderResults();});$('metric').addEventListener('change',renderChart);$('show-model').addEventListener('change',renderChart);$('attack-rate').addEventListener('input',renderChart);$('export-csv').addEventListener('click',exportTrials);$('export-summary').addEventListener('click',exportSummary);$('export-graph').addEventListener('click',()=>{const svg=$('chart').querySelector('svg');if(svg)download('<?xml version="1.0" encoding="UTF-8"?>\n'+svg.outerHTML,'functional-response-graph.svg','image/svg+xml;charset=utf-8');});
  $('clear-data').addEventListener('click',async()=>{if(await ask('Clear saved experiments?','This removes the experiments saved in this browser. Download your CSV files first; exported files will remain.','Clear experiments')){data={version:1,experiments:[],activeId:null};selectedId=null;save();renderSchedule();updateCounts();renderResults();$('prey-layer').replaceChildren();cover('<span class="cover-kicker">A FRESH START</span><h3>Ready for a new experiment.</h3><p>Choose your conditions and create a trial sequence.</p><button id="practice-again" class="light-button">Try a practice</button>');$('trial-badge').textContent='Ready to explore';$('activity-display').textContent='Ready';$('remaining-display').textContent='—';$('eaten-display').textContent='0';notify('Saved experiments cleared from this browser.');}});
  // Read-only access to the same recorded observations; never generates student data.
  if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_functional_response_results',title:'Read recorded functional response results',description:'Return the trial observations and experimental conditions already recorded in this browser. Does not play trials or generate data.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('Expected an empty object.');return{experiments:data.experiments.map(e=>({id:e.id,conditions:e.config,recorded_trials:e.trials,summary:M.summary(e.trials)}))};}})).catch(()=>{});}catch{}}
  restore();updateFormNotes();if(current()){fillForm(current().config);selectedId=current().id;renderReady();}renderSchedule();updateCounts();
})();
